version: '3.9'

services:

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: durka
      POSTGRES_DB: auth-database
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth
    environment:
      - SUPER-SECRET-KEY=fs1hk56jhldk12bv6dsh7
      - SUPER-SECRET-KEY-RE=mdhsz1pd1h6jhjldk1ds7
      - MAIL=hotelbooking02@mail.ru
      - EMAIL_PASSWORD=hPWFLzDD5mqWMPy1G1ty
      - SMTP_HOST=smtp.mail.ru
      - SMTP_PORT=465
      - DB_URL=postgres://postgres:durka@db:5432/auth-database?sslmode=disable
      - PORT=:8080
    ports:
      - "8080:8080" 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth-network  
    


volumes:
  postgres_data:

networks:
  auth-network:
    driver: bridge
